package Dashboard;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Dashboard {
    JFrame dashBoard;
    JPanel sideBar;
    JPanel users;
    JPanel locations;
    JPanel spots;
    JPanel billing;
    JPanel mostViewedSpots;
    JPanel bestRatedSpot;
    JPanel topPopularLocation;
    JPanel recentRegisteredSpots;
    JLabel DashboardLabel,UserLabel,BillingsLabel,LocationsLabel,SpotsLLabel,SettingsLabel,LogoutLabel,Users2Label,Locations2Label;
    JLabel dashboardIconLabel,usersIconLabel,billingsIconLabel,locationsIconLabel,spotsIconLabel,settingsIconLabel,logoutIconLabel,users2IconLabel,locations2IconLabel;
    ImageIcon icon1,icon2,icon3,icon4,icon5,icon6,icon7,icon8,icon9;
    BufferedImage img1,img2,img3,img4,img5,img6,img7,img8,img9;
    public Dashboard() throws IOException {
    dashBoard = new JFrame("Dashboard");
    sideBar = new JPanel();
    sideBar.setLayout(null);
    DashboardLabel = new JLabel("Dashboard");
    DashboardLabel.setFont(new Font("Roboto",Font.BOLD,20));
    DashboardLabel.setForeground(Color.white);
    img1 = ImageIO.read(new File("src\\images\\Dashboard.png"));
    icon1 = new ImageIcon(img1.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    dashboardIconLabel= new JLabel();
    dashboardIconLabel.setBounds(20,70,20,20);
    dashboardIconLabel.setIcon(icon1);
    DashboardLabel.setBounds(50,70,250,20);
    UserLabel = new JLabel("Users");
    UserLabel.setFont(new Font("Roboto",Font.BOLD,20));
    UserLabel.setForeground(Color.white);
    img2 = ImageIO.read(new File("src\\images\\users.png"));
    icon2 = new ImageIcon(img2.getScaledInstance(25,25,BufferedImage.SCALE_DEFAULT));
    usersIconLabel = new JLabel();
    usersIconLabel.setBounds(20,110,40,40);
    usersIconLabel.setIcon(icon2);
    UserLabel.setBounds(50,120,250,20);
    BillingsLabel = new JLabel("Billings");
    BillingsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    BillingsLabel.setForeground(Color.white);
    img3 = ImageIO.read(new File("src\\images\\Billing.png"));
    icon3 = new ImageIcon(img3.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    billingsIconLabel = new JLabel();
    billingsIconLabel.setBounds(20,200,20,20);
    billingsIconLabel.setIcon(icon3);
    BillingsLabel.setBounds(50,200,250,25);
    LocationsLabel = new JLabel("Locations");
    LocationsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    LocationsLabel.setForeground(Color.white);
    img4 = ImageIO.read(new File("src\\images\\Locations.png"));
    icon4 = new ImageIcon(img4.getScaledInstance(25,30,BufferedImage.SCALE_DEFAULT));
    locationsIconLabel = new JLabel();
    locationsIconLabel.setBounds(10,260,280,40);
    locationsIconLabel.setIcon(icon4);
    LocationsLabel.setBounds(10,270,250,25);
    SpotsLLabel = new JLabel("Spots");
    SpotsLLabel.setFont(new Font("Roboto",Font.BOLD,20));
    SpotsLLabel.setForeground(Color.white);
    img5 = ImageIO.read(new File("src\\images\\icons8_tripadvisor_64px 2.png"));
    icon5 = new ImageIcon(img5.getScaledInstance(30,30,BufferedImage.SCALE_DEFAULT));
    spotsIconLabel = new JLabel();
    spotsIconLabel.setBounds(20,350,250,25);
    spotsIconLabel.setIcon(icon5);
    SpotsLLabel.setBounds(52,350,250,25);

    SettingsLabel = new JLabel("Settings");
    SettingsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    SettingsLabel.setForeground(Color.white);
    img6 = ImageIO.read(new File("src\\images\\settings.png"));
    icon6 = new ImageIcon(img6.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    settingsIconLabel = new JLabel();
    settingsIconLabel.setBounds(20,420,250,25);
    settingsIconLabel.setIcon(icon6);
    SettingsLabel.setBounds(50,420,250,25);
    LogoutLabel = new JLabel("Logout");
    LogoutLabel.setBounds(50,520,250,25);
    LogoutLabel.setFont(new Font("Roboto",Font.BOLD,20));
    LogoutLabel.setForeground(Color.white);
    img7 = ImageIO.read(new File("src\\images\\logout.jpg"));
    icon7 = new ImageIcon(img7.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    logoutIconLabel = new JLabel();
    logoutIconLabel.setBounds(20,520,250,25);
    logoutIconLabel.setIcon(icon7);
    sideBar.add(dashboardIconLabel);
    sideBar.add(DashboardLabel);
    sideBar.add(usersIconLabel);
    sideBar.add(UserLabel);
    sideBar.add(billingsIconLabel);
    sideBar.add(BillingsLabel);
    sideBar.add(locationsIconLabel);
    sideBar.add(LocationsLabel);
    sideBar.add(spotsIconLabel);
    sideBar.add(SpotsLLabel);
    sideBar.add(settingsIconLabel);
    sideBar.add(SettingsLabel);
    sideBar.add(logoutIconLabel);
    sideBar.add(LogoutLabel);
    users = new JPanel();
    locations = new JPanel();
    spots = new JPanel();
    billing = new JPanel();
    mostViewedSpots = new JPanel();
    bestRatedSpot = new JPanel();
    topPopularLocation = new JPanel();
    recentRegisteredSpots = new JPanel();
    sideBar.setBounds(0,80,200,700);
    sideBar.setBackground(Color.decode("#3674d0"));
    users.setBounds(300,130,200,100);
    users.setLayout(null);
    users.setBackground(Color.decode("#fe3f3f"));
    img8 = ImageIO.read(new File("src\\images\\users2.png"));
    icon8 = new ImageIcon(img8.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    users2IconLabel = new JLabel();
    users2IconLabel.setBounds(80,15,400,40);
    users2IconLabel.setIcon(icon8);
    Users2Label = new JLabel("Users");
    Users2Label.setFont(new Font("Roboto",Font.BOLD,20));
    Users2Label.setForeground(Color.white);
    Users2Label.setBounds(80,20,100,100);
    users.add(users2IconLabel);
    users.add(Users2Label);
    locations.setBackground(Color.decode("#cd45d0"));
    locations.setBounds(550,130,200,100);
    locations.setLayout(null);
    img9 = ImageIO.read(new File("src\\images\\locations2.png"));
    icon9 = new ImageIcon(img9.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    locations2IconLabel = new JLabel();
    locations2IconLabel.setBounds(80,15,400,40);
    locations2IconLabel.setIcon(icon9);
    Locations2Label = new JLabel("Locations");
    Locations2Label.setFont(new Font("Roboto",Font.BOLD,20));
    Locations2Label.setForeground(Color.white);
    Locations2Label.setBounds(80,20,100,100);
    locations.add(locations2IconLabel);
    locations.add(Locations2Label);
    spots.setBackground(Color.decode("#42af60"));
    spots.setBounds(800,130,200,100);
    billing.setBackground(Color.decode("#4e5ef2"));
    billing.setBounds(1050,130,200,100);
    mostViewedSpots.setBackground(Color.white);
    mostViewedSpots.setBounds(300,280,180,150);
    bestRatedSpot.setBackground(Color.white);
    bestRatedSpot.setBounds(300,450,180,150);
    topPopularLocation.setBackground(Color.white);
    topPopularLocation.setBounds(550,285,300,300);
    recentRegisteredSpots.setBackground(Color.white);
    recentRegisteredSpots.setBounds(900,285,300,380);

    dashBoard.add(sideBar);
    dashBoard.add(users);
    dashBoard.add(locations);
    dashBoard.add(spots);
    dashBoard.add(billing);
    dashBoard.add(mostViewedSpots);
    dashBoard.add(bestRatedSpot);
    dashBoard.add(topPopularLocation);
    dashBoard.add(recentRegisteredSpots);
    dashBoard.setLayout(null);
    dashBoard.setSize(1920,900);
    dashBoard.setVisible(true);
 }
 public static void main(String args[]) throws IOException{
        new Dashboard();
 }
}
