package Dashboard;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Dashboard {
    JFrame dashBoard;
    JPanel sideBar;
    JPanel users;
    JPanel locations;
    JPanel spots;
    JPanel billing;
    JPanel mostViewedSpots;
    JPanel bestRatedSpot;
    JPanel topPopularLocation;
    JPanel recentRegisteredSpots;
    JLabel DashboardLabel,UserLabel,BillingsLabel,LocationsLabel,SpotsLLabel;
    JLabel dashboardIconLabel,usersIconLabel,billingsIconLabel,locationsIconLabel,spotsIconLabel;
    ImageIcon icon1,icon2,icon3,icon4,icon5;
    BufferedImage img1,img2,img3,img4,img5;
    public Dashboard() throws IOException {
    dashBoard = new JFrame("Dashboard");
    sideBar = new JPanel();
    sideBar.setLayout(null);
    DashboardLabel = new JLabel("Dashboard");
    DashboardLabel.setFont(new Font("Roboto",Font.BOLD,20));
    DashboardLabel.setForeground(Color.white);
    img1 = ImageIO.read(new File("src\\images\\Dashboard.png"));
    icon1 = new ImageIcon(img1.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    dashboardIconLabel= new JLabel();
    dashboardIconLabel.setBounds(20,70,20,20);
    dashboardIconLabel.setIcon(icon1);
    DashboardLabel.setBounds(50,70,250,20);
    UserLabel = new JLabel("Users");
    UserLabel.setFont(new Font("Roboto",Font.BOLD,20));
    UserLabel.setForeground(Color.white);
    img2 = ImageIO.read(new File("src\\images\\users.png"));
    icon2 = new ImageIcon(img2.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    usersIconLabel = new JLabel();
    usersIconLabel.setBounds(20,120,20,20);
    usersIconLabel.setIcon(icon2);
    UserLabel.setBounds(50,120,250,20);
    BillingsLabel = new JLabel("Billings");
    BillingsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    BillingsLabel.setForeground(Color.white);
    img3 = ImageIO.read(new File("src\\images\\Billing.png"));
    icon3 = new ImageIcon(img3.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    billingsIconLabel = new JLabel();
    billingsIconLabel.setBounds(20,200,20,20);
    billingsIconLabel.setIcon(icon3);
    BillingsLabel.setBounds(50,200,250,25);
    LocationsLabel = new JLabel("Locations");
    LocationsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    LocationsLabel.setForeground(Color.white);
    img4 = ImageIO.read(new File("src\\images\\Locations.png"));
    icon4 = new ImageIcon(img4.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    locationsIconLabel = new JLabel();
    locationsIconLabel.setBounds(20,270,250,25);
    locationsIconLabel.setIcon(icon4);
    LocationsLabel.setBounds(50,270,250,25);
    SpotsLLabel = new JLabel("Spots");
    SpotsLLabel.setFont(new Font("Roboto",Font.BOLD,20));
    SpotsLLabel.setForeground(Color.white);
    img5 = ImageIO.read(new File("src\\images\\icons8_tripadvisor_64px 2.png"));
    icon5 = new ImageIcon(img5.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    spotsIconLabel = new JLabel();
    spotsIconLabel.setBounds(20,350,250,25);
    spotsIconLabel.setIcon(icon5);
    SpotsLLabel.setBounds(50,350,250,25);
    sideBar.add(dashboardIconLabel);
    sideBar.add(DashboardLabel);
    sideBar.add(usersIconLabel);
    sideBar.add(UserLabel);
    sideBar.add(billingsIconLabel);
    sideBar.add(BillingsLabel);
    sideBar.add(locationsIconLabel);
    sideBar.add(LocationsLabel);
    sideBar.add(spotsIconLabel);
    sideBar.add(SpotsLLabel);
    users = new JPanel();
    locations = new JPanel();
    spots = new JPanel();
    billing = new JPanel();
    mostViewedSpots = new JPanel();
    bestRatedSpot = new JPanel();
    topPopularLocation = new JPanel();
    recentRegisteredSpots = new JPanel();
    sideBar.setBounds(0,80,200,700);
    sideBar.setBackground(Color.decode("#3674d0"));
    users.setBounds(300,130,200,100);
    users.setBackground(Color.decode("#fe3f3f"));
    locations.setBackground(Color.decode("#cd45d0"));
    locations.setBounds(550,130,200,100);
    spots.setBackground(Color.decode("#42af60"));
    spots.setBounds(800,130,200,100);
    billing.setBackground(Color.decode("#4e5ef2"));
    billing.setBounds(1050,130,200,100);
    mostViewedSpots.setBackground(Color.white);
    mostViewedSpots.setBounds(300,280,180,150);
    bestRatedSpot.setBackground(Color.white);
    bestRatedSpot.setBounds(300,450,180,150);
    topPopularLocation.setBackground(Color.white);
    topPopularLocation.setBounds(550,285,300,300);
    recentRegisteredSpots.setBackground(Color.white);
    recentRegisteredSpots.setBounds(900,285,300,380);

    dashBoard.add(sideBar);
    dashBoard.add(users);
    dashBoard.add(locations);
    dashBoard.add(spots);
    dashBoard.add(billing);
    dashBoard.add(mostViewedSpots);
    dashBoard.add(bestRatedSpot);
    dashBoard.add(topPopularLocation);
    dashBoard.add(recentRegisteredSpots);
    dashBoard.setLayout(null);
    dashBoard.setSize(1920,900);
    dashBoard.setVisible(true);
 }
 public static void main(String args[]) throws IOException{
        new Dashboard();
 }
}
