package client.Dashboard;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Dashboard {
    JFrame dashBoard;
    JPanel sideBar;
    JPanel users;
    JPanel locations;
    JPanel spots;
    JPanel billing;
    JPanel mostViewedSpots;
    JPanel bestRatedSpot;
    JPanel topPopularLocation;
    JPanel recentRegisteredSpots;
    JLabel DashboardLabel,UserLabel,BillingsLabel,LocationsLabel,SpotsLLabel,SettingsLabel,LogoutLabel,Users2Label,Locations2Label,spots2Label,billing2Label,RecentRegisterdSpotsLabel,recentRegisterdSpotsLabel,recentTimeLabel,bestRatedSpotLabel,bestRated2SpotLabel,bestRated3SpotLabel, bestRated4SpotLabel,bestRated5SpotLabel,bestRated6SpotLabel,bestRated7SpotLabel,bestRated8SpotLabel,mostViewedSpotsLabel,mostViewedSpotsLabel2;
    JLabel dashboardIconLabel,usersIconLabel,billingsIconLabel,locationsIconLabel,spotsIconLabel,settingsIconLabel,logoutIconLabel,users2IconLabel,locations2IconLabel,spots2IconLabel,billing2IconLabel,RecentRegisterdIconLabel,bestRatedIconSpotLabel,bestRated2IconSpotLabel,progressBar;
    ImageIcon icon1,icon2,icon3,icon4,icon5,icon6,icon7,icon8,icon9,icon10,icon11,icon12,icon13;
    BufferedImage img1,img2,img3,img4,img5,img6,img7,img8,img9,img10,img11,img12,img13;
    JProgressBar mostViewedSpotPb;
    JScrollPane scrollBar;
    Container container;
    public Dashboard() throws IOException {
    dashBoard = new JFrame("Dashboard");
    sideBar = new JPanel();
    sideBar.setLayout(null);
    DashboardLabel = new JLabel("Dashboard");
    DashboardLabel.setFont(new Font("Roboto",Font.BOLD,20));
    DashboardLabel.setForeground(Color.white);
    img1 = ImageIO.read(new File("src/client/images/Dashboard.png"));
    icon1 = new ImageIcon(img1.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    dashboardIconLabel= new JLabel();
    dashboardIconLabel.setBounds(20,70,20,20);
    dashboardIconLabel.setIcon(icon1);
    DashboardLabel.setBounds(50,70,250,20);
    UserLabel = new JLabel("Users");
    UserLabel.setFont(new Font("Roboto",Font.BOLD,20));
    UserLabel.setForeground(Color.white);
    img2 = ImageIO.read(new File("src\\client\\images\\users.png"));
    icon2 = new ImageIcon(img2.getScaledInstance(25,25,BufferedImage.SCALE_DEFAULT));
    usersIconLabel = new JLabel();
    usersIconLabel.setBounds(20,110,40,40);
    usersIconLabel.setIcon(icon2);
    UserLabel.setBounds(50,120,250,20);
    BillingsLabel = new JLabel("Billings");
    BillingsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    BillingsLabel.setForeground(Color.white);
    img3 = ImageIO.read(new File("src\\client\\images\\Billing.png"));
    icon3 = new ImageIcon(img3.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    billingsIconLabel = new JLabel();
    billingsIconLabel.setBounds(20,200,20,20);
    billingsIconLabel.setIcon(icon3);
    BillingsLabel.setBounds(50,200,250,25);
    LocationsLabel = new JLabel("Locations");
    LocationsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    LocationsLabel.setForeground(Color.white);
    img4 = ImageIO.read(new File("src\\client\\images\\Locations.png"));
    icon4 = new ImageIcon(img4.getScaledInstance(25,30,BufferedImage.SCALE_DEFAULT));
    locationsIconLabel = new JLabel();
    locationsIconLabel.setBounds(20,260,280,40);
    locationsIconLabel.setIcon(icon4);
    LocationsLabel.setBounds(45,270,250,25);
    SpotsLLabel = new JLabel("Spots");
    SpotsLLabel.setFont(new Font("Roboto",Font.BOLD,20));
    SpotsLLabel.setForeground(Color.white);
    img5 = ImageIO.read(new File("src\\client\\images\\icons8_tripadvisor_64px 2.png"));
    icon5 = new ImageIcon(img5.getScaledInstance(30,30,BufferedImage.SCALE_DEFAULT));
    spotsIconLabel = new JLabel();
    spotsIconLabel.setBounds(20,350,250,25);
    spotsIconLabel.setIcon(icon5);
    SpotsLLabel.setBounds(52,350,250,25);

    SettingsLabel = new JLabel("Settings");
    SettingsLabel.setFont(new Font("Roboto",Font.BOLD,20));
    SettingsLabel.setForeground(Color.white);
    img6 = ImageIO.read(new File("src\\client\\images\\settings.png"));
    icon6 = new ImageIcon(img6.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    settingsIconLabel = new JLabel();
    settingsIconLabel.setBounds(20,420,250,25);
    settingsIconLabel.setIcon(icon6);
    SettingsLabel.setBounds(50,420,250,25);
    LogoutLabel = new JLabel("Logout");
    LogoutLabel.setBounds(50,520,250,25);
    LogoutLabel.setFont(new Font("Roboto",Font.BOLD,20));
    LogoutLabel.setForeground(Color.white);
    img7 = ImageIO.read(new File("src\\client\\images\\logout.jpg"));
    icon7 = new ImageIcon(img7.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    logoutIconLabel = new JLabel();
    logoutIconLabel.setBounds(20,520,250,25);
    logoutIconLabel.setIcon(icon7);
    sideBar.add(dashboardIconLabel);
    sideBar.add(DashboardLabel);
    sideBar.add(usersIconLabel);
    sideBar.add(UserLabel);
    sideBar.add(billingsIconLabel);
    sideBar.add(BillingsLabel);
    sideBar.add(locationsIconLabel);
    sideBar.add(LocationsLabel);
    sideBar.add(spotsIconLabel);
    sideBar.add(SpotsLLabel);
    sideBar.add(settingsIconLabel);
    sideBar.add(SettingsLabel);
    sideBar.add(logoutIconLabel);
    sideBar.add(LogoutLabel);
    users = new JPanel();
    locations = new JPanel();
    spots = new JPanel();
    billing = new JPanel();
    mostViewedSpots = new JPanel();
    bestRatedSpot = new JPanel();
    topPopularLocation = new JPanel();
    recentRegisteredSpots = new JPanel();
    sideBar.setBounds(0,80,200,700);
    sideBar.setBackground(Color.decode("#3674d0"));
    users.setBounds(300,130,200,100);
    users.setLayout(null);
    users.setBackground(Color.decode("#fe3f3f"));
    img8 = ImageIO.read(new File("src\\client\\images\\users2.png"));
    icon8 = new ImageIcon(img8.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    users2IconLabel = new JLabel();
    users2IconLabel.setBounds(80,15,400,40);
    users2IconLabel.setIcon(icon8);
    Users2Label = new JLabel("Users");
    Users2Label.setFont(new Font("Roboto",Font.BOLD,20));
    Users2Label.setForeground(Color.white);
    Users2Label.setBounds(80,20,100,100);
    users.add(users2IconLabel);
    users.add(Users2Label);
    locations.setBackground(Color.decode("#cd45d0"));
    locations.setBounds(550,130,200,100);
    locations.setLayout(null);
    img9 = ImageIO.read(new File("src\\client\\images\\locations2.png"));
    icon9 = new ImageIcon(img9.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    locations2IconLabel = new JLabel();
    locations2IconLabel.setBounds(80,15,400,40);
    locations2IconLabel.setIcon(icon9);
    Locations2Label = new JLabel("Locations");
    Locations2Label.setFont(new Font("Roboto",Font.BOLD,20));
    Locations2Label.setForeground(Color.white);
    Locations2Label.setBounds(80,20,100,100);
    locations.add(locations2IconLabel);
    locations.add(Locations2Label);
    spots.setBackground(Color.decode("#42af60"));
    spots.setBounds(800,130,200,100);
    spots.setLayout(null);
    img10 =  ImageIO.read(new File("src\\client\\images\\icons8_tripadvisor_64px 2.png"));
    icon10 = new ImageIcon(img10.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    spots2IconLabel = new JLabel();
    spots2IconLabel.setBounds(80,15,400,40);
    spots2IconLabel.setIcon(icon10);
    spots2Label = new JLabel("Spots");
    spots2Label.setFont(new Font("Roboto",Font.BOLD,20));
    spots2Label.setForeground(Color.white);
    spots2Label.setBounds(80,20,100,100);
    spots.add(spots2IconLabel);
    spots.add(spots2Label);
    billing.setBackground(Color.decode("#4e5ef2"));
    billing.setBounds(1050,130,200,100);
    billing.setLayout(null);
    img11 = ImageIO.read(new File("src\\client\\images\\billing2.png"));
    icon11 = new ImageIcon(img11.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    billing2IconLabel = new JLabel();
    billing2IconLabel.setBounds(80,15,400,40);
    billing2IconLabel.setIcon(icon11);
    billing2Label = new JLabel("Billings");
    billing2Label.setFont(new Font("Roboto",Font.BOLD,20));
    billing2Label.setForeground(Color.white);
    billing2Label.setBounds(80,20,100,100);
    billing.add(billing2IconLabel);
    billing.add(billing2Label);
    mostViewedSpots.setBackground(Color.white);
    mostViewedSpots.setBounds(300,280,180,150);
    mostViewedSpots.setLayout(null);
    mostViewedSpotsLabel = new JLabel("Most viewed spots");
    mostViewedSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
    mostViewedSpotsLabel.setForeground(Color.gray);
    mostViewedSpotsLabel.setBounds(20,-70,200,200);
    mostViewedSpotsLabel2 = new JLabel("RCA:");
    mostViewedSpotsLabel2.setFont(new Font("Roboto",Font.BOLD,12));
    mostViewedSpotsLabel2.setForeground(Color.black);
    mostViewedSpotsLabel2.setBounds(20,-40,200,200);
    progressBar = new JLabel();
    progressBar.setBounds(40,-40,200,200);
    mostViewedSpotPb = new JProgressBar(0,2000);
    mostViewedSpotPb.setBounds(40,40,160,30);
    mostViewedSpotPb.setValue(0);
    mostViewedSpotPb.setStringPainted(true);
    progressBar.add(mostViewedSpotPb);
    mostViewedSpots.add(mostViewedSpotsLabel);
    mostViewedSpots.add(mostViewedSpotsLabel2);
    bestRatedSpot.setBackground(Color.white);
    bestRatedSpot.setBounds(300,450,180,150);
    bestRatedSpot.setLayout(null);
    bestRatedSpotLabel = new JLabel("Best rated spot");
    bestRatedSpotLabel.setFont(new Font("Roboto",Font.BOLD,15));
    bestRatedSpotLabel.setForeground(Color.gray);
    bestRatedSpotLabel.setBounds(20,-70,200,200);
    bestRatedIconSpotLabel = new JLabel("RCA:");
    bestRatedIconSpotLabel.setFont(new Font("Roboto",Font.BOLD,12));
    bestRatedIconSpotLabel.setForeground(Color.black);
    bestRatedIconSpotLabel.setBounds(20,-40,200,200);
    img13 = ImageIO.read(new File("src\\client\\images\\star.png"));
    icon13 = new ImageIcon(img13.getScaledInstance(20,20,BufferedImage.SCALE_DEFAULT));
    bestRated2SpotLabel = new JLabel();
    bestRated2SpotLabel.setBounds(48,-40,200,200);
    bestRated2SpotLabel.setIcon(icon13);
    bestRated3SpotLabel = new JLabel();
    bestRated3SpotLabel.setBounds(70,-40,200,200);
    bestRated3SpotLabel.setIcon(icon13);
    bestRated4SpotLabel = new JLabel();
    bestRated4SpotLabel.setBounds(90,-40,200,200);
    bestRated4SpotLabel.setIcon(icon13);
    bestRated5SpotLabel = new JLabel();
    bestRated5SpotLabel.setBounds(110,-40,200,200);
    bestRated5SpotLabel.setIcon(icon13);
    bestRated2IconSpotLabel = new JLabel("Nyamagabe:");
    bestRated2IconSpotLabel.setFont(new Font("Roboto",Font.BOLD,12));
    bestRated2IconSpotLabel.setForeground(Color.black);
    bestRated2IconSpotLabel.setBounds(20,-10,200,200);
    bestRated6SpotLabel = new JLabel();
    bestRated6SpotLabel.setBounds(90,-10,200,200);
    bestRated6SpotLabel.setIcon(icon13);
    bestRated7SpotLabel = new JLabel();
    bestRated7SpotLabel.setBounds(110,-10,200,200);
    bestRated7SpotLabel.setIcon(icon13);
    bestRated8SpotLabel = new JLabel();
    bestRated8SpotLabel.setBounds(130,-10,200,200);
    bestRated8SpotLabel.setIcon(icon13);
    bestRatedSpot.add(bestRatedSpotLabel);
    bestRatedSpot.add(bestRated2SpotLabel);
    bestRatedSpot.add(bestRated3SpotLabel);
    bestRatedSpot.add(bestRated4SpotLabel);
    bestRatedSpot.add(bestRated5SpotLabel);
    bestRatedSpot.add(bestRatedIconSpotLabel);
    bestRatedSpot.add(bestRated2IconSpotLabel);
    bestRatedSpot.add(bestRated6SpotLabel);
    bestRatedSpot.add(bestRated7SpotLabel);
    bestRatedSpot.add(bestRated8SpotLabel);
    topPopularLocation.setBackground(Color.white);
    topPopularLocation.setBounds(550,285,300,300);
    recentRegisteredSpots.setBackground(Color.white);
    recentRegisteredSpots.setBounds(900,285,300,380);
    recentRegisteredSpots.setLayout(null);
    recentRegisterdSpotsLabel = new JLabel("Recent registered spots");
    recentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
    recentRegisterdSpotsLabel.setForeground(Color.gray);
    recentRegisterdSpotsLabel.setBounds(30,-80,400,200);
    img12 = ImageIO.read(new File("src\\client\\images\\recentSpots1.png"));
    icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
    RecentRegisterdIconLabel = new JLabel();
    RecentRegisterdIconLabel.setBounds(20,50,400,40);
    RecentRegisterdIconLabel.setIcon(icon12);
    RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
    RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
    RecentRegisterdSpotsLabel.setBounds(80,-45,200,200);
    recentTimeLabel = new JLabel("2 minutes ago");
    recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
    recentTimeLabel.setForeground(Color.gray);
    recentTimeLabel.setBounds(80,-30,200,200);
    recentRegisteredSpots.add(recentRegisterdSpotsLabel);
    recentRegisteredSpots.add(RecentRegisterdIconLabel);
    recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
    recentRegisteredSpots.add(recentTimeLabel);


        img12 = ImageIO.read(new File("src\\client\\images\\recentSpots1.png"));
        icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
        RecentRegisterdIconLabel = new JLabel();
        RecentRegisterdIconLabel.setBounds(20,100,400,40);
        RecentRegisterdIconLabel.setIcon(icon12);
        RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
        RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
        RecentRegisterdSpotsLabel.setBounds(80,5,200,200);
        recentTimeLabel = new JLabel("2 minutes ago");
        recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
        recentTimeLabel.setForeground(Color.gray);
        recentTimeLabel.setBounds(80,25,200,200);
        recentRegisteredSpots.add(recentRegisterdSpotsLabel);
        recentRegisteredSpots.add(RecentRegisterdIconLabel);
        recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
        recentRegisteredSpots.add(recentTimeLabel);


        img12 = ImageIO.read(new File("src\\client\\images\\recentSpots1.png"));
        icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
        RecentRegisterdIconLabel = new JLabel();
        RecentRegisterdIconLabel.setBounds(20,150,400,40);
        RecentRegisterdIconLabel.setIcon(icon12);
        RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
        RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
        RecentRegisterdSpotsLabel.setBounds(80,60,200,200);
        recentTimeLabel = new JLabel("2 minutes ago");
        recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
        recentTimeLabel.setForeground(Color.gray);
        recentTimeLabel.setBounds(80,80,200,200);
        recentRegisteredSpots.add(recentRegisterdSpotsLabel);
        recentRegisteredSpots.add(RecentRegisterdIconLabel);
        recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
        recentRegisteredSpots.add(recentTimeLabel);


        img12 = ImageIO.read(new File("src\\client\\images\\recentSpots1.png"));
        icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
        RecentRegisterdIconLabel = new JLabel();
        RecentRegisterdIconLabel.setBounds(20,200,400,40);
        RecentRegisterdIconLabel.setIcon(icon12);
        RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
        RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
        RecentRegisterdSpotsLabel.setBounds(80,110,200,200);
        recentTimeLabel = new JLabel("2 minutes ago");
        recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
        recentTimeLabel.setForeground(Color.gray);
        recentTimeLabel.setBounds(80,130,200,200);
        recentRegisteredSpots.add(recentRegisterdSpotsLabel);
        recentRegisteredSpots.add(RecentRegisterdIconLabel);
        recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
        recentRegisteredSpots.add(recentTimeLabel);

        img12 = ImageIO.read(new File("src\\client\\images\\recentSpots1.png"));
        icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
        RecentRegisterdIconLabel = new JLabel();
        RecentRegisterdIconLabel.setBounds(20,250,400,40);
        RecentRegisterdIconLabel.setIcon(icon12);
        RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
        RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
        RecentRegisterdSpotsLabel.setBounds(80,160,200,200);
        recentTimeLabel = new JLabel("2 minutes ago");
        recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
        recentTimeLabel.setForeground(Color.gray);
        recentTimeLabel.setBounds(80,180,200,200);
        recentRegisteredSpots.add(recentRegisterdSpotsLabel);
        recentRegisteredSpots.add(RecentRegisterdIconLabel);
        recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
        recentRegisteredSpots.add(recentTimeLabel);


        icon12 = new ImageIcon(img12.getScaledInstance(40,40,BufferedImage.SCALE_DEFAULT));
        RecentRegisterdIconLabel = new JLabel();
        RecentRegisterdIconLabel.setBounds(20,300,400,40);
        RecentRegisterdIconLabel.setIcon(icon12);
        RecentRegisterdSpotsLabel = new JLabel("Mukamira District");
        RecentRegisterdSpotsLabel.setFont(new Font("Roboto",Font.BOLD,15));
        RecentRegisterdSpotsLabel.setBounds(80,210,200,200);
        recentTimeLabel = new JLabel("2 minutes ago");
        recentTimeLabel.setFont(new Font("Roboto",Font.BOLD,10));
        recentTimeLabel.setForeground(Color.gray);
        recentTimeLabel.setBounds(80,230,200,200);
        recentRegisteredSpots.add(recentRegisterdSpotsLabel);
        recentRegisteredSpots.add(RecentRegisterdIconLabel);
        recentRegisteredSpots.add(RecentRegisterdSpotsLabel);
        recentRegisteredSpots.add(recentTimeLabel);
        container = new Container();
        container.add(sideBar);
        container.add(users);
        container.add(locations);
        container.add(spots);
        container.add(billing);
        container.add(mostViewedSpots);
        container.add(bestRatedSpot);
        container.add(topPopularLocation);
        container.add(recentRegisteredSpots);
        scrollBar = new JScrollPane(container,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        container.setLayout(null);
        dashBoard.add(scrollBar);
        dashBoard.setSize(1920,1200);
        dashBoard.setVisible(true);
 }
 public void setProgressBarValue(){
        int i=0;
        try{
          while (i<=100){
           mostViewedSpotPb.setValue(i+10);
           Thread.sleep(1000);
           i+=20;
          }
        }catch (Exception ex){
            System.out.println(ex.getMessage());
        }
 }
 public static void main(String args[]) throws IOException{
       Dashboard dashboard = new Dashboard();
       dashboard.setProgressBarValue();
 }
}
